### ISSUE TITLE
Migrate away from calling `cabal` on file targets 

### ISSUE THREAD

**Issue by TeofilC** [haskell/hie-bios#427]
In https://github.com/haskell/cabal/pull/8966 cabal removed its support for file and module targets.
But these are currently used by `hie-bios` to determine the flags for components.
Perhaps we should just be calling `cabal repl` on the component instead?

See also the cabal issue: https://github.com/haskell/cabal/issues/9688

**Comment by mpickering** [comment]
I think that the patch in cabal should be reverted. This has been how `hie-bios` has interacted with `cabal-install` since the start of the library and it has been a stable and robust interface.

If this feature is removed then there should be a long deprecation period to avoid breaking HLS users who have old version of `hie-bios` and a suitable migration implemented in `hie-bios`.

**Comment by fendor** [comment]
This cabal PR slipped past me, otherwise I would have voiced this concern much sooner. Thanks for catching this *before* the next cabal release!

**Comment by TeofilC** [comment]
I'll close this for now since it looks like the cabal PR is getting reverted
